### ISSUE TITLE
Please add a license file & use ZSH plugin standard naming for the plugin file

### ISSUE THREAD

**Issue by unixorn** [dark-kitt/zsh-git-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Instead of a `.zshrc` file, please look at how the [ZSH Plugin Standard](https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html) names plugin files. TL;DR - name it `zsh-git-plugin.plugin.zsh` and most frameworks will automagically find and load the file.

Thanks!

**Comment by dark-kitt** [comment]
Hey, thanks for your hint.

LICENSE file was added and the plugin file was also renamed as `zsh-git-plugin.plugin.zsh`. 😉
